config/routes.rb
CodeRails3::Application.routes.draw do

  root :to => 'dashboard#index'
  match '' => 'dashboard#index', :as => 'dashboard'
  match '/help' => 'dashboard#help', :as => 'help'
  match '/force_exception' => 'application#force_exception'

  match '/login' => 'sessions#new', :as => 'login'
  match '/force_login' => 'sessions#create', :as => 'force_login'
  match '/logout' => 'sessions#destroy', :as => 'logout'
  match '/auth/cas/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/repository_directory' => 'repository_directory#index', :as => 'repository_directory'
  match '/repository_directory/:id' => 'repository_directory#show/:id', :as => 'repository_info'

  resource :profile, :only => [:edit, :update]

  resources :ssh_keys
  resource :invitation, :only => [:new, :create]

  resources :repositories, :except => :show do
    member do
      post :confirm_update
    end

    resources :collaborators, :except => [:new, :create, :destroy] do
      collection do
        get :edit
        post :update
        get :index
      end
    end
  end

  resources :spaces do
    member do
      post :confirm_update
    end

    resources :repositories, :controller => 'space_repositories'
    resources :deploy_keys, :except => [:show, :edit, :update], :controller => 'space_deploy_keys'
    resources :owners, :except => [:new, :create, :destroy], :controller => 'space_owners' do
      collection do
        get :edit
        post :update
        get :index
      end
    end
  end


  ###############################################################################
  ## Admin Routes
  ###############################################################################
  match '/admin' => 'admin/home#index', :as => 'admin_root'
  match '/admin' => 'admin/home#index', :as => 'admin'

  match '/admin/ldap_search' => 'admin/ldap_search# index', :as => 'admin_ldap_search'
  match '/admin/ldap_search/do_search' => 'admin/ldap_search#do_search', :as => 'admin_do_ldap_search'

  namespace(:admin) do
    resources :users, :except => :show do
      member do
        get :login
      end

      resources :ssh_keys, :except => [:show, :edit, :update]
      resources :collaborations, :only => [:index], :as => 'permissions', :controller => 'user_permissions'
    end

    resources :spaces do
      resources :repositories, :controller => 'space_repositories'
      resources :owners, :except => [:new, :create, :destroy], :controller => 'space_owners' do
        collection do
          get :edit
          post :update
          get :index
        end
      end
      resources :deploy_keys, :controller => 'space_deploy_keys', :except => 'show' do
        resources :collaborations, :only => [:index], :as => 'permissions', :controller => 'user_permissions'
      end
    end

    resources :repositories, :except => :show do
      member do
        get :create_svn_directory
        post :confirm_update
      end

      resources :collaborators, :except => [:new, :create, :destroy], :controller => 'collaborators' do
        collection do
          get :edit
          post :update
          get :index
        end
      end
    end
  end

  namespace :api do
    resources :repositories
  end

  scope "api" do
    match '/ldap_search' => 'api/ldap_search#find'
    match '/person_search' => 'api/ldap_search#person_search', :as => :ldap_person_search
    match '/base/test_auth' => 'api/base#test_auth'
    match '/web_data_loader/:action' => 'api/web_data_loader#:action'
    #match '/user_stats/:action/:username' => "api/user_stats#:action",
    #              :requirements => { :username => %r([^/;,?]+) }
    match '/repository_stats/:action/:space_name/:repo_name' => 'api/repository_stats#:action'
  end

  match '/cron_jobs/send_email' => 'cron_jobs#send_email'
  match '/cron_jobs/transition_search_plans' => 'cron_jobs#transition_search_plans'
end

app/controllers/admin/repository_collaborators_controller.rb
class Admin::RepositoryCollaboratorsController < Admin::BaseController
  before_filter(:repository)
  before_filter(:permissions)

  current_tab(:major, :repositories)
  current_tab(:minor, :collaborators)

  helper('admin/repository_tabs')
  # helper('repository_collaborators')
  helper('repositories')


  def index
    @collaborations = repository.collaborations
    @administrators = repository.administrators
  end

  def edit
    @users = repository.collaborators_available
    @administrators = repository.administrators
  end

  def update
    repository.update_collaborators_from_params(current_user, params)
    flash[:notice] = msg_updated("Collaborators")
    redirect_to(admin_repository_collaboration_url(repository, :id => ''))
  end

  
  protected

  def permissions
    @permissions = Collaboration.permissions
    @permissions.unshift("")
  end
  helper_method :permissions

  def repository
    @repository ||= Repository.find(params[:repository_id])
  end
  helper_method :repository

  def administrators
    @administrators
  end
  helper_method :administrators

  def collaborations
    @collaborations
  end
  helper_method :collaborations

  def users
    @users ||= User.all
  end
  helper_method :users
end

app/helpers/admin/repository_collaborators_helper.rb
module Admin::RepositoryCollaboratorsHelper
end

app/helpers/repository_collaborators_helper.rb
module RepositoryCollaboratorsHelper
  ##
  # Predicate that determines if the user has any permission for the
  # repository.
  #
  # @param [Repository]
  # @param [User]
  # @return [Boolean]
  #
  def has_access?(repo, user)
    RepositoryPermissionsService.permission_for(repo, user)
  end

  ##
  # Predicate that determines if the user specifically has "read" or "commit"
  # permission for a repository.
  #
  # @param [Repository]
  # @param [User]
  # @param [String] "commit" or "read"
  # @return [Boolean]
  #
  def has_permission?(repo, user, permission)
    RepositoryPermissionsService.permission_for(repo, user).try(:permission) == permission.to_s.downcase
  end

  ##
  # @param [Repository]
  # @param [User]
  # @return [String, nil] "commit", "read" or nil
  #
  def permission(repo, user)
    RepositoryPermissionsService.permission_for(repo, user).try(:permission)
  end

  def permission_widget(user, repo, permissions)
    if Space.administrator?(repo.space, user)
      Permission::COMMIT
    else
      select_tag(user.id, options_for_select(permissions, permission(repo, user)))
    end
  end

  ##
  # CSS string used to fade out a row for a user that already has permision
  # for a repository.
  #
  # @param [Repository]
  # @param [User]
  # @return [String]
  #
  def has_permission_css(repo, user)
    if has_access?(repo, user)
      "class='has_permission'"
    end
  end
end

app/views/admin/repository_collaborators/edit.html.erb
<% title(repository_title(repository)) %>

<%= render("admin/repositories/repository_detail", :repository => repository) %>

<div style="text-align: center;">
    <%= render("/layouts/invitation") %>
</div>


<%= form_tag(:method => "post", :controller => "admin/repository_collaborators", :action => "update", :id => "") do %>
    <%= submit_tag("Update Collaborators", :class => "btn btn-primary") %> or
    <%= link_to("Back", admin_repository_collaborations_url(repository)) %>
    <br/><br/>

    <p><strong>Note:</strong> <em>Permissions for Space Administrators can only be changed at the Space level.</em></p>

    <table id="users" class="table table-bordered">
        <thead>
            <tr>
                <th>Full Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Space Admin?</th>
                <th>Permission</th>
            </tr>
        </thead>
        <tbody class="highlight">
            <% administrators.each do |admin| %>
                <tr id="<%= dom_id(admin) %>" <%= has_permission_css(repository, admin) %>>
                    <td><%= h(admin.full_name) %></td>
                    <td><%= h(admin.username) %></td>
                    <td><%= h(admin.email) %></td>
                    <td><%= boolean_check_mark(true) %></td>
                    <td><%= permission_widget(admin, repository, permissions) %></td>
                </tr>
            <% end %>

            <% users.each do |user| %>
                <tr id="<%= dom_id(user) %>" <%= has_permission_css(repository, user) %>>
                    <td><%= h(user.full_name) %></td>
                    <td><%= h(user.username) %></td>
                    <td><%= h(user.email) %></td>
                    <td></td>
                    <td><%= permission_widget(user, repository, permissions) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/admin/repository_collaborators/index.html.erb
<%= title("Repository: #{repository.canonical_name}") %>


<%= render("admin/repositories/repository_detail", :repository => repository) %>

<div class="row-fluid">
    <div class="span3">
        <%= minor_tabs(repository).html %>
    </div>

    <div class="span9">
        <div class="boxed-group">
            <h3>Collaborators</h3>

            <div class="boxed-group-inner">
                <%= link_to("Edit Collaborators", edit_admin_repository_collaboration_url(repository, :id => ""), :class => "btn btn-small btn-primary") %>
                <br/><br/>
                <table id="collaborators" class="table table-condensed">
                    <tr>
                        <th>Full Name</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Space Admin?</th>
                        <th>Permission</th>
                    </tr>
                    <tbody class="highlight">
                        <% administrators.each do |admin| %>
                            <tr id="<%= dom_id(admin) %>">
                                <td><%= h(admin.full_name) %></td>
                                <td><%= h(admin.username) %></td>
                                <td><%= h(admin.email) %></td>
                                <td><%= boolean_check_mark(true) %></td>
                                <td><%= Permission::COMMIT %></td>
                            </tr>
                        <% end %>

                        <% collaborations.each do |c| %>
                            <tr id="<%= dom_id(c) %>">
                                <td><%= h(c.user.full_name) %></td>
                                <td><%= h(c.user.username) %></td>
                                <td><%= h(c.user.email) %></td>
                                <td></td>
                                <td><%= h(c.permission) %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>