config/routes.rb
CodeRails3::Application.routes.draw do

  root :to => 'dashboard#index'
  match '' => 'dashboard#index', :as => 'dashboard'
  match '/help' => 'dashboard#help', :as => 'help'
  match '/force_exception' => 'application#force_exception'

  match '/login' => 'sessions#new', :as => 'login'
  match '/force_login' => 'sessions#create', :as => 'force_login'
  match '/logout' => 'sessions#destroy', :as => 'logout'
  match '/auth/cas/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/repository_directory' => 'repository_directory#index', :as => 'repository_directory'
  match '/repository_directory/:id' => 'repository_directory#show/:id', :as => 'repository_info'

  resource :profile, :only => [:edit, :update]

  resources :ssh_keys
  resource :invitation, :only => [:new, :create]

  resources :repositories, :except => :show do
    member do
      post :confirm_update
    end

    resources :collaborators, :except => [:new, :create, :destroy] do
      collection do
        get :edit
        post :update
        get :index
      end
    end
  end

  resources :spaces do
    member do
      post :confirm_update
    end

    resources :repositories, :controller => 'space_repositories'
    resources :deploy_keys, :except => [:show, :edit, :update], :controller => 'space_deploy_keys'
    resources :owners, :except => [:new, :create, :destroy], :controller => 'space_owners' do
      collection do
        get :edit
        post :update
        get :index
      end
    end
  end


  ###############################################################################
  ## Admin Routes
  ###############################################################################
  match '/admin' => 'admin/home#index', :as => 'admin_root'
  match '/admin' => 'admin/home#index', :as => 'admin'

  match '/admin/ldap_search' => 'admin/ldap_search# index', :as => 'admin_ldap_search'
  match '/admin/ldap_search/do_search' => 'admin/ldap_search#do_search', :as => 'admin_do_ldap_search'

  namespace(:admin) do
    resources :users, :except => :show do
      member do
        get :login
      end

      resources :ssh_keys, :except => [:show, :edit, :update]
      resources :collaborations, :only => [:index], :as => 'permissions', :controller => 'user_permissions'
    end

    resources :spaces do
      resources :repositories, :controller => 'space_repositories'
      resources :owners, :except => [:new, :create, :destroy], :controller => 'space_owners' do
        collection do
          get :edit
          post :update
          get :index
        end
      end
      resources :deploy_keys, :controller => 'space_deploy_keys', :except => 'show' do
        resources :collaborations, :only => [:index], :as => 'permissions', :controller => 'user_permissions'
      end
    end

    resources :repositories, :except => :show do
      member do
        get :create_svn_directory
        post :confirm_update
      end

      resources :collaborators, :except => [:new, :create, :destroy], :controller => 'collaborators' do
        collection do
          get :edit
          post :update
          get :index
        end
      end
    end
  end

  namespace :api do
    resources :repositories
  end

  scope "api" do
    match '/ldap_search' => 'api/ldap_search#find'
    match '/person_search' => 'api/ldap_search#person_search', :as => :ldap_person_search
    match '/base/test_auth' => 'api/base#test_auth'
    match '/web_data_loader/:action' => 'api/web_data_loader#:action'
    #match '/user_stats/:action/:username' => "api/user_stats#:action",
    #              :requirements => { :username => %r([^/;,?]+) }
    match '/repository_stats/:action/:space_name/:repo_name' => 'api/repository_stats#:action'
  end

  match '/cron_jobs/send_email' => 'cron_jobs#send_email'
  match '/cron_jobs/transition_search_plans' => 'cron_jobs#transition_search_plans'
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  include SizeMethods

  default_scope includes(:space).order('name')

  belongs_to :space
  belongs_to :owner, :class_name => 'User', :foreign_key => 'user_id'
  has_many :collaborations, :dependent => :delete_all
  has_many :collaborators, :through => :collaborations, :source => :user, :order => 'name'

  delegate :name, :to => :space, :prefix => true
  delegate :name, :email, :to => :owner, :prefix => true

  validates_presence_of :name, :space_id, :user_id
  validates_uniqueness_of :name, :scope => :space_id
  validates :name, :entity_name => { allow_blank: true }

  def disk_usage
    size_display
  end

  def committers
    collaborators.keep_if { |collaborator| collaborator.permission == Permission::COMMIT }
  end

  def readers
    collaborators.keep_if { |collaborator| collaborator.permission == Permission::READ }
  end

  def canonical_name
    [space.name, name].join(' / ')
  end

  def url
    "svn+ssh://#{App.svn_username}@#{App.svn_connection_url}/#{space.name}/#{name}"
  end
end

app/controllers/admin/repositories_controller.rb
class Admin::RepositoriesController < Admin::BaseController
  current_tab(:major, :repositories)
  current_tab(:minor, :detail, :only => [:edit, :update])

  helper('admin/repository_tabs', :repositories)

  def index
    @repositories = Repository.find_by_space_name(params[:space])
  end
  
  def new
    @repository = Repository.new
  end
  
  def create
    @repository = Repository.new(repo_params)
    if @repository.save
      flash[:success] = msg_created(@repository)
      redirect_to(edit_admin_repository_path(@repository))
    else
      render('new')
    end
  end
  
  def edit
  end

  def update
    repository.attributes = repo_params

    if repository.valid? && Repository.confirmation_required?(repository)
      render('confirm_update')
    elsif repository.save
      flash[:success] = msg_updated(repository)
      redirect_to(edit_admin_repository_path(repository))
    else
      render("edit")
    end
  end

  def confirm_update
    repository.update_attributes(repo_params)

    if params[:perform_notification]
      msg = RepositoryUrlChangedMessage.new_from_repository_params(current_user, params[:repo_changed])
      CollaboratorMailer.deliver_repository_url_changed_notification(msg)
    end

    flash[:success] = msg_updated(repository)
    redirect_to(edit_admin_repository_path(repository))
  end

  def destroy
    repository.destroy
    flash[:success] = msg_destroyed(repository)
    redirect_to(admin_repositories_path)
  end

  def create_svn_directory
    if !repository.svn_dir_exists?
      repository.create_svn_repository
      flash[:success] = "SVN Directory has been created."
    end
    redirect_to(edit_admin_repository_path(repository))
  end

  protected

  def repo_params
    params.require(:repository).permit!
  end

  def repositories
    @repositories
  end
  helper_method :repositories

  def repository
    @repository ||= Repository.find(params[:id])
  end
  helper_method :repository

  def spaces
    @spaces ||= Space.all.inject({}) do |hash, space|
      hash[space.name] = space.id
      hash
    end
  end
  helper_method :spaces
end

app/controllers/api/repositories_controller.rb
class Api::RepositoriesController < ApplicationController
  respond_to :json

  def index
    respond_with(Repository.all, :root => false)
  end

end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  helper(RepositoryTabsHelper)

  current_tab(:major, :repositories)
  no_minor_tabs(:only => [:index, :new, :create])
  current_tab(:minor, :detail, :only => [:edit, :update])


  def index
    @repositories = current_user.repositories
  end
  
  def new
    @spaces = current_user.spaces_owned
    @repository = current_user.repositories.build
  end

  def create
    @spaces = current_user.spaces_owned

    repo_creator.create(repo_params)
    @repository = repo_creator.repository

    if @repository.persisted?
      redirect_to(edit_repository_path(@repository), :flash => { success: msg_created(@repository) })
    else
      render('new')
    end
  end

  def edit
    @spaces = current_user.spaces_owned
    @repository = current_user.repositories.find(params[:id])
  end

  # TODO: restore confirmation behaviour since repository name (or space)
  # change will change the connection url
  def update
    @spaces = current_user.spaces_owned
    @repository = current_user.repositories.find(params[:id])
    @repository.attributes = repo_params

    if @repository.save
      redirect_to(edit_repository_path(@repository), :flash => { success: msg_updated(@repository) })
    else
      render('edit')
    end
  end

  def destroy
    @repository = current_user.repositories.find(params[:id])
    @repository.destroy
    redirect_to(repositories_path, :flash => { success: msg_destroyed(@repository) })
  end


private

  def repo_params
    params.require(:repository).permit(:space_id, :name, :description)
  end

  def repo_creator
    @repo_creator ||= RepositoryService::Creator.new(:current_user => current_user)
  end

end

app/helpers/admin/repositories_helper.rb
module Admin::RepositoriesHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper

  def repository_title(repo)
    "#{link_to(repo.space.name, space_path(repo.space))} / #{link_to(repo.name, edit_repository_path(repo))}"
  end

  # Returns the select options for the 'edit' action
  def spaces_for_new(user)
    options = user.spaces.
        all(:order => 'name').
        map { |space| [space.name, space.id] }
    options << ['Create in NEW Space', 0]
  end
  
  # Returns repo's current space to populate r/o select for "Old Space"
  def spaces_for_old_space(repo)
    space = repo.space
    [[space.name, space.id]]
  end
  
  # Returns the select option for repo's edit space.
  def spaces_for_new_space(user, repo)
    user.spaces.
        all(:order => 'name').
        reject { |space| space == repo.space }.
        map { |space| [space.name, space.id] }
  end

  def url_was(repository)
    name = App.svn_username
    host = App.svn_connection_url
    space = Space.find(repository.space_id_was).name
    "svn+ssh://#{name}@#{host}/#{space}/#{repository.name_was}"
  end

end

app/views/repositories/_form.html.haml
= simple_form_for(@repository, :html => {class: 'form-horizontal'}) do |f|
  = f.input(:space_id, :required => true, :as => :select, :collection => @spaces, :prompt => 'Select One')
  = f.input(:name)
  = f.input(:description, :input_html => { :rows => 4, :columns => 10 })

  = form_actions do
    = save_button(f)
    %span or
    = link_to_cancel(repositories_path)

app/views/repositories/_no_repositories.html.haml
%tr
  %td{ :colspan => colspan }
    There are no repositories

app/views/repositories/_repository_detail.html.haml
%blockquote
  %p= "Owner: #{repository.owner_name}"

%div.row-fluid
  %form.form-horizontal.repository-clone
    %div.input-prepend
      %span.add-on SVN URL
      %input#prependedInput{ :type => 'text', :value => repository.url }

app/views/repositories/confirm_update.html.erb
<% title("Confirm Repository Update") %>


<% set_bread_crumbs(:repositories_crumb, edit_repository_crumb(@repo), "Confirm Update") %>


<div class="page_content mid_width">
  <div class="ui-widget">
    <div class="ui-state-error ui-corner-all" style="padding: 0 .7em; margin-right: 1em;">
      <p style="font-size: 11pt;">
        <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
        <strong>Alert:</strong> you are about to make a serous change to your repository.
        Please read the following information carefully before confirming these changes.
      </p>
    </div>
  </div>

  <br/>

  <p>
    <em style="font-size: 14pt;">
      Changing the name and/or space of a repository will cause its URL to change. If you
      perform this update, all users of this repository will need to update their SVN
      connection information in order to continue accessing this repository.
    </em>
  </p>

  <br/>

  <table>
    <tr>
      <th>Current SVN URL:</th>
      <td><%= url_was(@repo) %></td>
    </tr>
    <tr>
      <th>Updated SVN URL:</th>
      <td><%= @repo.url() %></td>
    </tr>
  </table>

  <br/>

  <h3>Email Repository Collaborators</h3>
  <% form_tag(confirm_update_repository_url(@repo)) do %>
      <p>
        <%= hidden_field_tag("repository[space_id]", @repo.space_id()) %>
        <%= hidden_field_tag("repository[name]", @repo.name()) %>
        <%= hidden_field_tag("repository[description]", @repo.description()) %>

        <%= hidden_field_tag("repo_changed[id]", @repo.id()) %>
        <%= hidden_field_tag("repo_changed[url_was]", url_was(@repo)) %>
      </p>

      <p>
        <%= check_box_tag("perform_notification", 1, true) %>
        Send email notification of this change to all collaborators of this repository.
      </p>

      <p>
        <%= label_tag("repo_changed[message]", "Email Message") %><br/>
        <%= text_area_tag("repo_changed[message]", nil, :size => "80x10") %>
      </p>

      <p>
        <%= submit_tag("Yes - Perform Update", :class => "button_widget") %>
        <%= link_to("Cancel", edit_repository_url(@repo)) %>
      </p>
  <% end %>
</div>

app/views/repositories/confirm_update.html.haml
<% title("Confirm Repository Update") %>


<% set_bread_crumbs(:repositories_crumb, edit_repository_crumb(@repo), "Confirm Update") %>


<div class="page_content mid_width">
  <div class="ui-widget">
    <div class="ui-state-error ui-corner-all" style="padding: 0 .7em; margin-right: 1em;">
      <p style="font-size: 11pt;">
        <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
        <strong>Alert:</strong> you are about to make a serous change to your repository.
        Please read the following information carefully before confirming these changes.
      </p>
    </div>
  </div>

  <br/>

  <p>
    <em style="font-size: 14pt;">
      Changing the name and/or space of a repository will cause its URL to change. If you
      perform this update, all users of this repository will need to update their SVN
      connection information in order to continue accessing this repository.
    </em>
  </p>

  <br/>

  <table>
    <tr>
      <th>Current SVN URL:</th>
      <td><%= url_was(@repo) %></td>
    </tr>
    <tr>
      <th>Updated SVN URL:</th>
      <td><%= @repo.url() %></td>
    </tr>
  </table>

  <br/>

  <h3>Email Repository Collaborators</h3>
  <% form_tag(confirm_update_repository_url(@repo)) do %>
      <p>
        <%= hidden_field_tag("repository[space_id]", @repo.space_id()) %>
        <%= hidden_field_tag("repository[name]", @repo.name()) %>
        <%= hidden_field_tag("repository[description]", @repo.description()) %>

        <%= hidden_field_tag("repo_changed[id]", @repo.id()) %>
        <%= hidden_field_tag("repo_changed[url_was]", url_was(@repo)) %>
      </p>

      <p>
        <%= check_box_tag("perform_notification", 1, true) %>
        Send email notification of this change to all collaborators of this repository.
      </p>

      <p>
        <%= label_tag("repo_changed[message]", "Email Message") %><br/>
        <%= text_area_tag("repo_changed[message]", nil, :size => "80x10") %>
      </p>

      <p>
        <%= submit_tag("Yes - Perform Update", :class => "button_widget") %>
        <%= link_to("Cancel", edit_repository_url(@repo)) %>
      </p>
  <% end %>
</div>

app/views/repositories/edit.html.haml
- title('Account')
= account_major_tabs.html

%br

= render('repository_detail', :repository => @repository)

%div.row-fluid
  %div.span3
    = minor_tabs(@repository).html
  %div.span9
    %div.boxed-group
      %h3 Repository Detail
      %div.boxed-group-inner
        = render('form', :repository => @repository, :spaces => @spaces)

    = delete_button_to(@repository, :label => 'Delete this Repository')

app/views/repositories/index.html.haml
- title('Account')
= account_major_tabs.html

%br

= link_to_new('New Repository', new_repository_path)

%table#repositories{:class => table_style }
  %thead
    %tr
      %th Repository
      %th Space
      %th Owner
      %th Last Commit
      %th Created At
  %tbody
    - if @repositories.empty?
      = render('no_repositories', :colspan => 5)
    - else
      - @repositories.each do |repo|
        %tr{:id => dom_id(repo) }
          %td
            %i.icon-pencil
            = link_to(repo.name, edit_repository_path(repo))
          %td= link_to(repo.space.name, edit_space_path(repo.space))
          %td= repo.owner.name
          %td= repo.committed_at.try(:to_s, :mdy)
          %td= repo.created_at.try(:to_s, :mdy)

app/views/repositories/new.html.haml
- title('Account')
= account_major_tabs.html

%br

= render('form')