config/routes.rb
CodeRails3::Application.routes.draw do

  root :to => 'dashboard#index'
  match '' => 'dashboard#index', :as => 'dashboard'
  match '/help' => 'dashboard#help', :as => 'help'
  match '/force_exception' => 'application#force_exception'

  match '/login' => 'sessions#new', :as => 'login'
  match '/force_login' => 'sessions#create', :as => 'force_login'
  match '/logout' => 'sessions#destroy', :as => 'logout'
  match '/auth/cas/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/repository_directory' => 'repository_directory#index', :as => 'repository_directory'
  match '/repository_directory/:id' => 'repository_directory#show/:id', :as => 'repository_info'

  resource :profile, :only => [:edit, :update]

  resources :ssh_keys
  resource :invitation, :only => [:new, :create]

  resources :repositories, :except => :show do
    member do
      post :confirm_update
    end

    resources :collaborators, :except => [:new, :create, :destroy] do
      collection do
        get :edit
        post :update
        get :index
      end
    end
  end

  resources :spaces do
    member do
      post :confirm_update
    end

    resources :repositories, :controller => 'space_repositories'
    resources :deploy_keys, :except => [:show, :edit, :update], :controller => 'space_deploy_keys'
    resources :owners, :except => [:new, :create, :destroy], :controller => 'space_owners' do
      collection do
        get :edit
        post :update
        get :index
      end
    end
  end


  ###############################################################################
  ## Admin Routes
  ###############################################################################
  match '/admin' => 'admin/home#index', :as => 'admin_root'
  match '/admin' => 'admin/home#index', :as => 'admin'

  match '/admin/ldap_search' => 'admin/ldap_search# index', :as => 'admin_ldap_search'
  match '/admin/ldap_search/do_search' => 'admin/ldap_search#do_search', :as => 'admin_do_ldap_search'

  namespace(:admin) do
    resources :users, :except => :show do
      member do
        get :login
      end

      resources :ssh_keys, :except => [:show, :edit, :update]
      resources :collaborations, :only => [:index], :as => 'permissions', :controller => 'user_permissions'
    end

    resources :spaces do
      resources :repositories, :controller => 'space_repositories'
      resources :owners, :except => [:new, :create, :destroy], :controller => 'space_owners' do
        collection do
          get :edit
          post :update
          get :index
        end
      end
      resources :deploy_keys, :controller => 'space_deploy_keys', :except => 'show' do
        resources :collaborations, :only => [:index], :as => 'permissions', :controller => 'user_permissions'
      end
    end

    resources :repositories, :except => :show do
      member do
        get :create_svn_directory
        post :confirm_update
      end

      resources :collaborators, :except => [:new, :create, :destroy], :controller => 'collaborators' do
        collection do
          get :edit
          post :update
          get :index
        end
      end
    end
  end

  namespace :api do
    resources :repositories
  end

  scope "api" do
    match '/ldap_search' => 'api/ldap_search#find'
    match '/person_search' => 'api/ldap_search#person_search', :as => :ldap_person_search
    match '/base/test_auth' => 'api/base#test_auth'
    match '/web_data_loader/:action' => 'api/web_data_loader#:action'
    #match '/user_stats/:action/:username' => "api/user_stats#:action",
    #              :requirements => { :username => %r([^/;,?]+) }
    match '/repository_stats/:action/:space_name/:repo_name' => 'api/repository_stats#:action'
  end

  match '/cron_jobs/send_email' => 'cron_jobs#send_email'
  match '/cron_jobs/transition_search_plans' => 'cron_jobs#transition_search_plans'
end

app/controllers/space_owners_controller.rb
class SpaceOwnersController < ApplicationController
  before_filter(:find_space)

  current_tab(:major, :spaces)
  current_tab(:minor, :owners)

  helper(SpaceTabsHelper)
  helper(SpacesHelper)


  def index
    @owners = @space.owners
  end

  def edit
    @users = @space.owners_available
  end

  def update
    owner_updater.update(owner_ids)
    redirect_to(space_owners_url(@space), :flash => { success: msg_updated("Owners") })
  end


  private

  def owner_ids
    (params[:owner_ids] || {}).keys
  end

  def owner_updater
    @owner_updater ||= SpaceService::OwnerUpdater.new(:current_user => current_user, :space => @space)
  end

  def find_space
    @space = current_user.spaces_owned.find(params[:space_id])
  end

end

app/helpers/space_owners_helper.rb
module SpaceOwnersHelper

  ##
  # Predicate that determines if the user has any permission for the
  # repository.
  #
  # @param [Repository]
  # @param [User]
  # @return [Boolean]
  #
  def admin?(space, user)
    Space.administrator?(space, user)
  end

  ##
  # @param [Repository]
  # @param [User]
  # @return [String, nil] "admin" or ""
  #
  def permission(space, user)
    admin?(space, user) ? "admin" : ""
  end

  def permissions()
    ["admin", ""]
  end

  ##
  # CSS string used to fade out a row for a user that is an admin
  # for a space.
  #
  # @param [Space]
  # @param [User]
  # @return [String]
  #
  def has_permission_css(space, user)
    if admin?(space, user)
      "class='has_permission'"
    end
  end

end

app/views/space_owners/edit.html.haml
= title(space_title(@space))
= link_to('&larr; Back'.html_safe, space_owners_url(@space))

%div
= render(:partial => '/layouts/invitation')

= form_tag(:method => 'post', :controller => 'space_owners', :action => 'update') do
  = submit_tag('Update Owners', :class => 'btn btn-primary')
  %br
  %br

  %table#users{ :class => table_style }
    %thead
      %tr
        %th Owner?
        %th Full Name
        %th Username
        %th Email

    %tbody
      - @users.each do |user|
        %tr{ :id => dom_id(user) }
          %td= space_owner_check_box(user, @space)
          %td= user.name
          %td= user.username
          %td= user.email

app/views/space_owners/index.html.haml
= title(space_title(@space))

%div.row-fluid
  %div.span3
    = minor_tabs(@space).html
  %div.span9
    %div.boxed-group
      %h3 Space Owners
      %div.boxed-group-inner
        = link_to_new('Edit', edit_space_owners_url(@space))
        - unless @owners.empty?
          %table#space_owners{ :class => table_style }
            %thead
              %tr
                %th Username
                %th Full Name
                %th Email
            %tbody
              - @owners.each do |owner|
                %tr{ :id => dom_id(owner) }
                  %td= owner.username
                  %td= owner.name
                  %td= owner.email