config/routes.rb
CodeRails3::Application.routes.draw do

  root :to => 'dashboard#index'
  match '' => 'dashboard#index', :as => 'dashboard'
  match '/help' => 'dashboard#help', :as => 'help'
  match '/force_exception' => 'application#force_exception'

  match '/login' => 'sessions#new', :as => 'login'
  match '/force_login' => 'sessions#create', :as => 'force_login'
  match '/logout' => 'sessions#destroy', :as => 'logout'
  match '/auth/cas/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/repository_directory' => 'repository_directory#index', :as => 'repository_directory'
  match '/repository_directory/:id' => 'repository_directory#show/:id', :as => 'repository_info'

  resource :profile, :only => [:edit, :update]

  resources :ssh_keys
  resource :invitation, :only => [:new, :create]

  resources :repositories, :except => :show do
    member do
      post :confirm_update
    end

    resources :collaborators, :except => [:new, :create, :destroy] do
      collection do
        get :edit
        post :update
        get :index
      end
    end
  end

  resources :spaces do
    member do
      post :confirm_update
    end

    resources :repositories, :controller => 'space_repositories'
    resources :deploy_keys, :except => [:show, :edit, :update], :controller => 'space_deploy_keys'
    resources :owners, :except => [:new, :create, :destroy], :controller => 'space_owners' do
      collection do
        get :edit
        post :update
        get :index
      end
    end
  end


  ###############################################################################
  ## Admin Routes
  ###############################################################################
  match '/admin' => 'admin/home#index', :as => 'admin_root'
  match '/admin' => 'admin/home#index', :as => 'admin'

  match '/admin/ldap_search' => 'admin/ldap_search# index', :as => 'admin_ldap_search'
  match '/admin/ldap_search/do_search' => 'admin/ldap_search#do_search', :as => 'admin_do_ldap_search'

  namespace(:admin) do
    resources :users, :except => :show do
      member do
        get :login
      end

      resources :ssh_keys, :except => [:show, :edit, :update]
      resources :collaborations, :only => [:index], :as => 'permissions', :controller => 'user_permissions'
    end

    resources :spaces do
      resources :repositories, :controller => 'space_repositories'
      resources :owners, :except => [:new, :create, :destroy], :controller => 'space_owners' do
        collection do
          get :edit
          post :update
          get :index
        end
      end
      resources :deploy_keys, :controller => 'space_deploy_keys', :except => 'show' do
        resources :collaborations, :only => [:index], :as => 'permissions', :controller => 'user_permissions'
      end
    end

    resources :repositories, :except => :show do
      member do
        get :create_svn_directory
        post :confirm_update
      end

      resources :collaborators, :except => [:new, :create, :destroy], :controller => 'collaborators' do
        collection do
          get :edit
          post :update
          get :index
        end
      end
    end
  end

  namespace :api do
    resources :repositories
  end

  scope "api" do
    match '/ldap_search' => 'api/ldap_search#find'
    match '/person_search' => 'api/ldap_search#person_search', :as => :ldap_person_search
    match '/base/test_auth' => 'api/base#test_auth'
    match '/web_data_loader/:action' => 'api/web_data_loader#:action'
    #match '/user_stats/:action/:username' => "api/user_stats#:action",
    #              :requirements => { :username => %r([^/;,?]+) }
    match '/repository_stats/:action/:space_name/:repo_name' => 'api/repository_stats#:action'
  end

  match '/cron_jobs/send_email' => 'cron_jobs#send_email'
  match '/cron_jobs/transition_search_plans' => 'cron_jobs#transition_search_plans'
end

app/models/user.rb
class User < ActiveRecord::Base

  default_scope order('name')

  scope :active, :conditions => { active: true }
  scope :admin, :conditions => { admin: true }
  scope :administrators, :conditions => { admin: true }
  scope :eligible_collaborators, :conditions => { active: true, agreed_to_terms: true }

  has_many :ssh_keys, :as => :ssh_key_authenticatable, :dependent => :delete_all
  has_many :collaborations
  # has_many :repositories, :through => :collaborations, :source => :repository
  has_many :repositories
  # has_many :repositories_owned, :through => :collaborations

  has_many :space_ownerships, :dependent => :delete_all
  has_many :spaces_owned, :through => :space_ownerships, :source => :space
  has_many :spaces, :through => :space_ownerships, :source => :space

  validates_presence_of :ldap_uid, :name, :email, :username
  validates :username, :username => { allow_blank: true }
  validates_acceptance_of :agreed_to_terms, :accept => true
  validates_uniqueness_of :ldap_uid, :email, :allow_blank => true
  validates :email, :email => { allow_blank: true }


  def default_space
    (spaces_owned.size == 1) ? spaces_owned.first : nil
  end

  def to_s
    "%s / %s / %s)" % [name, username, email]
  end

  def self.new_from_ldap_uid(ldap_uid)
    User.new
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter(:find_user, :only => [:edit, :update, :destroy, :login])

  current_tab(:major, :users)
  current_tab(:minor, :detail, :only => [:edit, :update])
  no_minor_tabs(:except => [:edit, :update])

  helper('admin/users')

  def index
    @users = User.all
  end

  def new
    @user = User.new_from_ldap_uid(params[:ldap_uid])
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save!
    redirect_to(edit_admin_user_url(@user), :flash => { success: msg_created(@user) })
  rescue ActiveRecord::RecordInvalid
    render("new")
  end

  def update
    if user.update_attributes(user_params)
      redirect_to(edit_admin_user_url(user), :flash => { success: msg_updated(user) })
    else
      render("edit")
    end
  end

  def destroy
    if user.destroy
      redirect_to(admin_users_url, :flash => { success: msg_destroyed(user) })
    else
      flash[:error] = user.errors.full_messages.join(",")
      redirect_to(edit_admin_user_url(user))
    end
  end

  def login
    application_login(user.ldap_uid)
    redirect_to(root_url)
  end

  protected

  def user_params
    params.require(:user).permit!
  end

  def find_user
    @user ||= User.find(params[:id])
  end

  def user
    @user
  end

  helper_method :user

  def users
    @users ||= User.all
  end

  helper_method :users
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

  def user_left_nav_tabs(user)
    TabNav::TabSet.new(self, :name => :minor) do |ts|
      ts.add(:detail, edit_admin_user_url(user))
      ts.add(:ssh_keys, admin_user_ssh_keys_url(user), :label => "SSH Keys")
      ts.add(:permissions, admin_user_permissions_url(user))
    end
  end

  def user_title(user)
    "#{user.name} (#{user.username})"
  end

  def date_or_none(date, format=:ymd_hms)
    date.try(:to_s, format) || "n/a"
  end
end

app/views/admin/users/_form.html.haml
= simple_form_for([:admin, user], :html => {class: 'form-horizontal'}) do |f|
  - disabled = !f.object.new_record?

  = f.input(:username, :disabled => disabled, :as => :string)
  = f.input(:ldap_uid, :disabled => disabled, :as => :string)
  = f.input(:name, :hint => '')
  = f.input(:email)

  %br
  %hr
  %br

  = f.input(:admin)
  = f.input(:active)
  = f.input(:agreed_to_terms)

  = form_actions do
    = save_button(f)
    %span or
    = link_to_cancel(admin_users_path)

app/views/admin/users/_user_date_stats.html.haml
%table.table.table-condensed.table-hover
  %tbody
    %tr
      %th Last Login
      %td= date_or_none(user.last_login)
    %tr
      %th Last SVN Access
      %td= date_or_none(user.last_svn_access)
    %tr
      %th Created At
      %td= date_or_none(user.created_at)
    %tr
      %th Updated At
      %td= date_or_none(user.updated_at)

app/views/admin/users/edit.html.haml
%div= title(user_title(user))

%div.row-fluid
  %div.span3
    = user_left_nav_tabs(user).html
    %div.boxed-group
      %h3 User Date Stats
      %div.boxed-group-inner
        = render(:partial => "user_date_stats", :user => user)
        = button_to("Login As User", login_admin_user_path(user), :method => :get, :class => 'btn-primary')
  %div.span9
    %div.boxed-group
      %h3 User Details
      %div.boxed-group-inner
        = render('form', :user => user)
        = delete_button_to([:admin, user], :label => "Delete this User")

app/views/admin/users/index.html.haml
%div= title("Users (#{users.length})")

= link_to_new("New User", new_admin_user_path)

%table{ :id => "users", :class => "table table-bordered"}
  %thead
    %tr
      %th Username
      %th Name
      %th Email
      %th Ldap Uid
      %th Last SVN Access
      %th Last Login
      %th Admin?

    %tbody
      - users.each do |user|
        %tr{ :id => dom_id(user) }
          %td
            %i.icon-pencil
            = link_to(user.username, edit_admin_user_path(user))
          %td= user.name
          %td= user.email
          %td= user.ldap_uid
          %td= date_or_none(user.last_svn_access, :mdy)
          %td= date_or_none(user.last_login, :mdy)
          %td= boolean_check_mark(user.admin)

app/views/admin/users/new.html.haml
= title("New User")

-#%div= link_to("Lookup User in LDAP", ldap_search_url("ldap_search[search_for]" => 'user'), :class => "btn btn-primary btn-mini")

= render('form')